[".config/alacritty/themes"]
type = "git-repo"
url = "https://github.com/eendroroy/alacritty-theme.git"
exact = true
stripComponents = 1

[".config/zsh/oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".config/zsh/custom/themes/powerlevel10k"]
type = "git-repo"
url = "https://github.com/romkatv/powerlevel10k.git"
exact = true
stripComponents = 1
refreshPeriod = "168h"
